[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.9.2"
edition = "2021"
license = "MIT"
rust-version = "1.81"
authors = ["clabby", "refcell"]
homepage = "https://github.com/anton-rs/superchain"
repository = "https://github.com/anton-rs/superchain"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["benches/", "tests/"]

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[patch.crates-io]
kona-derive = { git = "https://github.com/anton-rs/kona", branch = "main" }

[workspace.dependencies]
# Workspace
superchain-derive = { version = "0.9.2", path = "crates/derive", default-features = false }
superchain-registry = { version = "0.9.2", path = "crates/registry", default-features = false }

# Kona
kona-derive = { version = "0.0.5", default-features = false }

# Alloy
alloy-rlp = { version = "0.3.9", default-features = false }
alloy-eips = { version = "0.6.1", default-features = false }
alloy-serde = { version = "0.6.1", default-features = false }
alloy-provider = { version = "0.6.1", default-features = false }
alloy-primitives = { version = "0.8.11", default-features = false }
alloy-consensus = { version = "0.6.1", default-features = false }
alloy-transport = { version = "0.6.1", default-features = false }
alloy-rpc-client = { version = "0.6.1", default-features = false }
alloy-node-bindings = { version = "0.6.1", default-features = false }
alloy-transport-http = { version = "0.6.1", default-features = false }
alloy-rpc-types-beacon = { version = "0.6.1", default-features = false }

# OP Alloy
op-alloy-genesis = { version = "0.6.2", default-features = false }
op-alloy-protocol = { version = "0.6.2", default-features = false }
op-alloy-consensus = { version = "0.6.2", default-features = false }

# Serialization
serde = { version = "1.0.214", default-features = false }
serde_json = { version = "1.0.132", default-features = false }

# Misc
lru = "0.12.5"
tokio = "1.41.0"
reqwest = "0.12.9"
async-trait = "0.1.83"
tracing = { version = "0.1.40", default-features = false }
derive_more = { version = "1.0.0", default-features = false }
lazy_static = { version = "1.5.0", default-features = false }
