[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.9.2"
edition = "2021"
license = "MIT"
rust-version = "1.81"
authors = ["clabby", "refcell"]
homepage = "https://github.com/anton-rs/superchain"
repository = "https://github.com/anton-rs/superchain"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["benches/", "tests/"]

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
# Alloy
alloy-eips = { version = "0.5.4", default-features = false }
alloy-primitives = { version = "0.8.9", default-features = false }

# Op Alloy
op-alloy-genesis = { version = "0.5.1", default-features = false }

# Serialization
serde = { version = "1.0.213", default-features = false }
serde_json = { version = "1.0.132", default-features = false }

# Misc
lazy_static = { version = "1.5.0", default-features = false }
