[package]
name = "superchain"
description = "The Superchain Registry"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["anton-rs"]
repository = "https://github.com/anton-rs/superchain"
homepage = "https://github.com/anton-rs/superchain"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
superchain-primitives = { workspace = true, version = "0.2.2", default-features = false }

# `serde` is optional, but enabled by default
# Since superchain-registry requires `serde`, we mark it as optional
superchain-registry = { workspace = true, version = "0.2.6", optional = true, default-features = false }

[features]
default = ["serde", "std"]

serde = [
  "dep:superchain-registry",
  "superchain-primitives/serde",
]

std = [
  "serde",
  "dep:superchain-registry",
  "superchain-registry/std",
  "superchain-primitives/std",
]
