name: no_std

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-no-std:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        package: ["super-registry"]
    name: check no_std ${{ matrix.features }} ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
      - run: cargo check --target riscv32imac-unknown-none-elf --no-default-features -p ${{ matrix.package }}
