name: Release Crates

on:
  workflow_dispatch:

jobs:
  release-crates:
    name: Release Crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo release
        run: cargo install cargo-release
      - name: Login to cargo
        run: cargo login $CARGO_REGISTRY_TOKEN
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Release superchain crate
        run: just release
        continue-on-error: true
